// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a simplified placeholder - run 'make proto' to generate from admin.proto

package adminpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// Request and Response types
type AddLearnerRequest struct {
	NodeId  string
	Address string
}

type AddLearnerResponse struct {
	Success bool
	Message string
}

type PromoteRequest struct {
	NodeId string
}

type PromoteResponse struct {
	Success bool
	Message string
}

type RemoveNodeRequest struct {
	NodeId string
}

type RemoveNodeResponse struct {
	Success bool
	Message string
}

type CaughtUpRequest struct {
	NodeId string
}

type CaughtUpResponse struct {
	CaughtUp bool
	Message  string
}

type TransferLeaderRequest struct {
	TargetNodeId string
}

type TransferLeaderResponse struct {
	Success bool
	Message string
}

type StatusResponse struct {
	Leader  string
	Members []*Member
}

type Member struct {
	NodeId   string
	Role     string
	CaughtUp bool
}

// AdminServiceClient interface
type AdminServiceClient interface {
	AddLearner(ctx context.Context, in *AddLearnerRequest, opts ...grpc.CallOption) (*AddLearnerResponse, error)
	Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error)
	RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*RemoveNodeResponse, error)
	CaughtUp(ctx context.Context, in *CaughtUpRequest, opts ...grpc.CallOption) (*CaughtUpResponse, error)
	TransferLeader(ctx context.Context, in *TransferLeaderRequest, opts ...grpc.CallOption) (*TransferLeaderResponse, error)
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
}

// AdminServiceServer interface
type AdminServiceServer interface {
	AddLearner(context.Context, *AddLearnerRequest) (*AddLearnerResponse, error)
	Promote(context.Context, *PromoteRequest) (*PromoteResponse, error)
	RemoveNode(context.Context, *RemoveNodeRequest) (*RemoveNodeResponse, error)
	CaughtUp(context.Context, *CaughtUpRequest) (*CaughtUpResponse, error)
	TransferLeader(context.Context, *TransferLeaderRequest) (*TransferLeaderResponse, error)
	GetStatus(context.Context, *emptypb.Empty) (*StatusResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded for forward compatibility
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) AddLearner(context.Context, *AddLearnerRequest) (*AddLearnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLearner not implemented")
}

func (UnimplementedAdminServiceServer) Promote(context.Context, *PromoteRequest) (*PromoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Promote not implemented")
}

func (UnimplementedAdminServiceServer) RemoveNode(context.Context, *RemoveNodeRequest) (*RemoveNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNode not implemented")
}

func (UnimplementedAdminServiceServer) CaughtUp(context.Context, *CaughtUpRequest) (*CaughtUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CaughtUp not implemented")
}

func (UnimplementedAdminServiceServer) TransferLeader(context.Context, *TransferLeaderRequest) (*TransferLeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferLeader not implemented")
}

func (UnimplementedAdminServiceServer) GetStatus(context.Context, *emptypb.Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}

func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}

// RegisterAdminServiceServer registers the service
func RegisterAdminServiceServer(s *grpc.Server, srv AdminServiceServer) {
	// Simplified registration - actual implementation would register handlers
	_ = s
	_ = srv
}
