apiVersion: storage.sys/v1
kind: RaftCluster
metadata:
  name: bug1-demo
spec:
  replicas: 3
  image: localhost:5000/raft-kv:latest
  storageSize: 1Gi
  snapshotInterval: "30s"
  electionTimeoutMs: 300
  safetyMode: unsafe-early-vote  # Bug 1: Early-Vote Learner
  reconfig:
    rateLimit: "1/min"
    maxParallel: 1
    cooldownSeconds: 60
